# Generated by Django 4.2.7 on 2023-12-13 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('adres_zamieszkania', models.CharField(max_length=12)),
                ('nr_tel', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zwierzak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('rasa', models.CharField(max_length=100)),
                ('data_przyjecia', models.DateField()),
                ('stan_zdrowia', models.CharField(default='zdrowy', max_length=30)),
                ('opis', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('godzina_od', models.TimeField()),
                ('godzina_do', models.TimeField()),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schronisko.klient')),
                ('zwierzak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schronisko.zwierzak')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramLojalnosciowy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schronisko.klient')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaLeczenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('opis', models.CharField(max_length=3000)),
                ('zwierzak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schronisko.zwierzak')),
            ],
        ),
        migrations.CreateModel(
            name='Boks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokalizacja', models.CharField(max_length=300)),
                ('zwierzak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schronisko.zwierzak')),
            ],
        ),
        migrations.CreateModel(
            name='Adopcja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schronisko.klient')),
                ('zwierzak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schronisko.zwierzak')),
            ],
        ),
    ]
