# Generated by Django 4.2.7 on 2023-12-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schronisko', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='adres_zamieszkania',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='klient',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='klient',
            name='nr_tel',
            field=models.CharField(max_length=12),
        ),
    ]
