# Generated by Django 4.2.9 on 2024-01-02 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('aq_date', models.DateField()),
                ('health_state', models.CharField(default='zdrowy', max_length=30)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour_from', models.TimeField()),
                ('hour_to', models.TimeField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schronisko.animal')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schronisko.client')),
            ],
        ),
        migrations.CreateModel(
            name='Playpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localization', models.CharField(max_length=300)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schronisko.animal')),
            ],
        ),
        migrations.CreateModel(
            name='LoyalityProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schronisko.client')),
            ],
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=3000)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schronisko.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schronisko.animal')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schronisko.client')),
            ],
        ),
    ]
